### ISSUE TITLE
Can't sign back in with Google

### ISSUE THREAD

**Issue by haemaenpaa** [danieldickison/kachiclash#20]
When using a Google account to sign in, I'm getting an error page that says

````
Database error: Database error: no such column: user_id
````

Steps to reproduce:

1. Click "Sign in"
1. Click "Login with Google"
1. The first time you log in works fine
1. Log out
1. Repeat steps 1. and 2.

**Comment by danieldickison** [comment]
Thanks for the bug report! There was an issue with logging in with google if you've changed your profile pic in google since your last login. It's fixed now. lmk if you continue to see issues.
